-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2021. Nov 01. 12:48
-- Kiszolgáló verziója: 10.4.17-MariaDB
-- PHP verzió: 8.0.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `faloda`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `receptek`
--

CREATE TABLE `receptek` (
  `ssz` int(2) NOT NULL,
  `etel` varchar(50) COLLATE utf8mb4_hungarian_ci NOT NULL,
  `etel_url` varchar(50) COLLATE utf8mb4_hungarian_ci NOT NULL,
  `elkeszites` int(3) NOT NULL,
  `ar` enum('olcsó','átlagos','megfizethető','költséges') COLLATE utf8mb4_hungarian_ci NOT NULL,
  `foto` varchar(55) COLLATE utf8mb4_hungarian_ci NOT NULL,
  `leiras` text COLLATE utf8mb4_hungarian_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

--
-- A tábla adatainak kiíratása `receptek`
--

INSERT INTO `receptek` (`ssz`, `etel`, `etel_url`, `elkeszites`, `ar`, `foto`, `leiras`) VALUES
(1, 'krumplis tészta', 'krumplisteszta', 45, 'megfizethető', 'krumplisteszta.jpg', 'A hagymát kockára vágjuk és a felforrósított olajon megpirítjuk. Megszórjuk pirospaprikával, majd hozzáadjuk a meghámozott, kockára vágott burgonyát, és felöntjük annyi vízzel, hogy ellepje. Sóval, borssal ízesítjük, és lassú tűzön megfőzzük. Amikor a krumpli már puha, összetörjük villával vagy burgonyatörővel. A tésztát a csomagoláson található előírás szerint forró vízben kifőzzük, majd hozzákeverjük a tört burgonyához. Savanyúsággal tálalhatjuk.'),
(2, 'rakott krumpli', 'rakott-krumpli', 90, 'átlagos', 'rakott-krumpli.jpg', 'A krumplikat 10-15 percre beáztatjuk hideg vízbe, majd alaposan megsikáljuk és leöblítjük. A tojásokat megmossuk. A krumplit annyi hideg vízzel öntjük fel, hogy bőven ellepje. Hozzáadjuk a sót, és a forrástól számított 20 percig, fedő alatt puhára főzzük. A tojásokat sós, hideg vízben feltesszük főni, és a forrástól számított 8 percig főzzük, majd hideg vízbe merítve azonnal lehűtjük. A krumpliról leöntjük a vizet, még melegen meghámozzuk, és hűlni hagyjuk. A kihűlt tojásokat is meghámozzuk, elnegyedeljük vagy felkarikázzuk. A kolbászt meleg vízzel leöblítjük, így könnyen lehúzhatjuk a héját, aztán vékonyan felkarikázzuk. Elkeverjük a tejfölben a tojássárgákat. A sütőt 180 fokra (gázsütő 3. fokozat) előmelegítjük. A vajjal kikenünk egy lapos, tűzálló tálat, aljára karikázzuk a krumpli felét, kissé megsózzuk, lazán összekeverjük, és elsimítjuk. Arányosan elosztva a tetejére rendezzük a tojást és a kolbászkarikákat, majd megkenjük a tejföl felével. A maradék krumplit felkarikázzuk, és kissé egymásra csúsztatva a tetejére rendezzük. Egyenletesen bevonjuk a maradék tejföllel, végül a tetejére göndörítjük a szalonnaszeleteket. A sütőben addig sütjük, amíg a tejföl és a szalonna aranybarnára pirul (35-40 perc). Vegyes idénysalátával vagy ecetes savanyúsággal tálaljuk.'),
(3, 'vadas zsemlegombóccal', 'vadas-zsemlegomboccal', 90, 'költséges', 'vadas-zsemlegomboccal.jpg', 'A húst felszeleteljük, megsózzuk, megborsozzuk, megforgatjuk lisztben, majd forró olajban hirtelen kisütjük. Papírszalvétára szedjük, és lecsepegtetjük. A húsokat ezután egy nagyobb lábasba tesszük. A megtisztított sárgarépát, fehérrépát, felszeletelt vöröshagymát, babérlevelet, egész borsot, ízlés szerint sót, mustárt és az apróra vágott szalonnát a húsra tesszük. Felöntjük kb. 1 liter vízzel, és feltesszük főni. Addig főzzük, amíg a hús meg nem puhul. A közben elfőtt vizet pótoljuk. A megpuhult húsokat, a babérleveleket és a borsszemeket kiszedjük. A zöldségekről ezután leszűrjük a levet, és mindkettőt félretesszük. A zöldségeket botmixerrel összeturmixoljuk, közben olajon megkaramellizáljuk a  cukrot. Ha a cukor megbarnult, ráöntjük a zöldségturmixot, kicsit összeforraljuk, és elkeverjük benne a lisztet, majd felengedjük a félretett lével, és jól összeforraljuk. A tejfölhöz hozzáadunk 1 ek lisztet, összekeverjük, majd a mártáshoz adjuk. Felforraljuk, majd beletesszük a húsokat. Ha szükséges, tovább ízesítjük. Közben elkészítjük mellé a zsemlegombócot, melyhez a zsemlét felkockázzuk és megpirítjuk. A lisztből, tojásból és tejből nokedlitésztát készítünk, és beletesszük a zsemlekockákat, valamint a felaprított petrezselyemzöldet. A masszából gombócokat formázunk, majd forró vízben kifőzzük mindet. A vadas mellett köretként tálaljuk.'),
(4, 'brassói aprópecsenye', 'brassoi-apropecsenye', 60, 'megfizethető', 'brassoi-apropecsenye.jpg', 'A húst 2×2 cm-es darabokra felkockázzuk. A szalonnát ujjnyi vastag csíkokra vágjuk és egy serpenyőben megpirítjuk. Hozzáadjuk az apró kockára vágott vöröshagymát is és üvegesre pirítjuk, majd a zúzott fokhagymát is. A paradicsomot és a paprikát nagyobb darabokra vágjuk és a hagymás alaphoz keverjük. Kissé megpároljuk, majd hozzáadjuk a felkockázott sertéshúst, és megsózzuk, megborsozzuk. Addig pirítjuk, míg szép fehér színe lesz a húsnak, eközben pedig levet ereszt. Pirospaprikával megszórjuk és felöntjük annyi vízzel amennyi épp ellepi. Kb. 40-45 percig főzzük, amíg a hús megpuhul. A burgonyát megpucoljuk és kockára vágjuk. Bő olajban kisütjük, ezután konyhai papírtörlőre szedjük, hogy lecsöpögjön a felesleges zsiradék. A brassói aprópecsenyét a sült burgonya kockákkal tálaljuk. Frissen aprított petrezselyemzölddel megszórva kínáljuk.'),
(5, 'paprikás krumpli', 'paprikas-krumpli', 45, 'olcsó', 'paprikas-krumpli.jpg', 'A hagymát megtisztítjuk és kockára vágjuk. Kevés olajat forrósítunk egy lábasban, beletesszük a hagymát, üvegesre pirítjuk, hozzáadjuk a felkarikázott kolbászt, majd megpirítjuk. Lehúzzuk a lábast a tűzhelyről, megszórjuk a pirospaprikával. Átkeverjük, majd hozzáadjuk a megmosott, megtisztított és kockára vágott burgonyát, és felöntjük annyi vízzel, ami majdnem ellepi. Megsózzuk, paradicsompürét teszünk bele, és addig főzzük, amíg a burgonya megpuhul. Friss kenyérrel, savanyú uborkával tálaljuk.'),
(6, 'babgulyás', 'babgulyas', 90, 'megfizethető', 'babgulyas.jpg', 'Forró zsiradékon megpirítjuk a finomra aprított vöröshagymát, rajta megfuttatjuk a zúzott fokhagymát és a köményt, a felkockázott marhahúst rátesszük, pár percig dinszteljük, amíg a hús kifehéredik. A tűzről lehúzzuk, megszórjuk pirospaprikával elkeverjük, és felengedjük annyi vízzel, amennyi bőven ellepi. Amíg a leves felforr, a beáztatott babot előfőzzük: bő vízben, a forrástól számított 5 perc múlva a puffasztó levét leöntjük, a forró babot a forró leveshez adjuk. (Hideg vízhez ne adjuk, mert a forró bab megedződik, és nehezebben puhul meg.) Ha kell, vizet öntünk rá, hogy bőven ellepje. A levest fűszerezzük sóval, borssal, majoránnával, babérral, és takarékon főzzük tovább. Amikor félpuha a hús, belerakjuk a zöldséget, a zöldséglevél-csokrot, az egész paprikát, a paradicsomot, és további vizet adunk hozzá, sóval, fűszerekkel utánaízesítjük, majd takarékon puhára főzzük. A főzés ideje alatt a tojásból, a lisztből, egy csipet sóval, egy kis tálban kemény (levestészta keménységű) tésztát gyúrunk, kicsit pihentetjük, majd enyhén lisztezett tálcára csipegetjük. Amikor a hús és a bab puha, a csipetkét is beleadjuk, és pár perc alatt készre főzzük. Tálalás előtt a főtt zöldséglevél csokrot, zöldpaprikát, paradicsomot eltávolítjuka levesből.'),
(7, 'tejfölös csirkepaprikás tarhonyával', 'tejfolos-csirkepaprikas-tarhonyaval', 90, 'megfizethető', 'tejfolos-csirkepaprikas-tarhonyaval.jpg', 'A megtiszított, megmosott és szárazra törölt csirkét feldaraboljuk. A vöröshagymát apróra vágjuk. A paradicsomot és a paprikát felszeleteljük. Az olajon elkezdjük üvegesre párolni a vöröshagymát, majd pár perc után hozzáadjuk a felszeletelt paradicsomot és a paprikát. Ezután még pár percig pároljuk, majd ráhelyezzük a feldarabolt csirkét. A hús mindkét oldalát fehéredésig sütjük, majd megszórjuk a pirospaprikával, rákanalazzuk a Piros Aranyat és az ízlés szerinti mennyiségű Erős Pistát, majd alaposan összekeverjük. Ezután felöntjük annyi vízzel, hogy éppen csak ellepje a húst, majd megsózzuk és megszórjuk a fűszerekkel. Végül hozzáadjuk a tejfölt, majd alaposan összekeverjük. Ezután az edényen résnyi helyet hagyva lefedjük, majd felforraljuk a levet. Amikor már forr, kisebb lángra vesszük, és szép lassan puhára főzzük a húst. A tarhonyát aranybarnára pirítjuk egy kevés olajon, majd felöntjük kétszeres mennyiségű vízzel. Ízlés szerint megsózzuk, majd átöntjük egy jénai tálba, és lefedjük. Végül mikróba tesszük, és alacsony fokozaton 25 percig mikrózzuk (sütőben is elkészíthetjük). Tálaláskor a tejfölös csirkepaprikást a tarhonyával és savanyúsággal kínáljuk.'),
(8, 'töltött paprika', 'toltott-paprika', 75, 'átlagos', 'toltott-paprika.jpg', 'A hagymát finomra aprítjuk, majd megfonnyasztjuk az olajon a zúzott fokhagymával együtt. A tűzről lehúzva megszórjuk őrölt pirospaprikával, majd, ha már nem forró, alaposan összekeverjük a darált hússal és az előzőleg félig megfőzött rizzsel. Megsózzuk, megborsozzuk alaposan. A paprikákat kicsumázzuk, megtöltjük a darálthúsos-rizses töltelékkel (ne töltsük túl, hagyjunk helyet a megduzzadó rizsnek). A maradék töltelékből gombócokat formázunk. A hagymát negyedekre vágjuk, és megpirítjuk egy kevés olajon. Megszórjuk a cukorral, majd a liszttel, és csomómentesre keverjük. Folyamatosan kevergetve hozzáöntjük a paradicsomszószt, felhúzzuk a vízzel, beletesszük a zellert, és megsózzuk, megborsozzuk. Óvatosan beletesszük a megtöltött paprikákat, és alacsony lángon, néha megforgatva kb. 30-40 percig főzzük, amíg a töltelék teljesen megfő. Ha szükséges, egy kevés vízzel vagy alaplével pótoljuk az elfőtt folyadékot. A megpucolt és kockázott burgonyákat sós vízben megfőzzük. A megfőtt töltött paprikát a paradicsommártással és burgonyával tálaljuk.'),
(9, 'húsleves', 'husleves', 90, 'átlagos', 'husleves.jpg', 'A csontot feldaraboljuk, és egy nagyobb fazékban, annyi hideg vízben feltesszük főni, ami egy tenyérnyire ellepi. Közepes vagy magasabb hőfokon kb. 15 percig forraljuk, a habját leszedjük. Visszavéve a hőfokot, belepakoljuk a zöldségeket: a megtiszított répákat egészben, a zellert és a karalábét almagerezd méretűre vágva, a vöröshagymát héjastul, a paradicsomot és a paprikát. A borsszemeket és a fokhagymát egy teatojásba téve, a petrezselymet cérnával összekötözve rakjuk a levesbe. Igény szerint 1-2 szem krumpli is belekerülhet. Ha minden benne van, nagyon alacsony hőfokon, éppen, hogy csak pezsegjen, elkezdjük főzni a levest. 3-4 órán át főzzük, addig, míg villával megszúrva a zöldségeket és a húst nem érezzük omlósan puhának őket. A főzési idő vége előtt kb. fél órával sózzuk a levest, de aki szereti, hogy a zöldségek és a hús is sós legyen, már az elején is beleteheti. Ha minden benne van, nagyon alacsony hőfokon, éppen, hogy csak pezsegjen, elkezdjük főzni a levest. 3-4 órán át főzzük, addig, míg villával megszúrva a zöldségeket és a húst nem érezzük omlósan puhának őket. A főzési idő vége előtt kb. fél órával sózzuk a levest, de aki szereti, hogy a zöldségek és a hús is sós legyen, már az elején is beleteheti. A tálaláshoz lefejjük a főtt húst a csontról, levestésztát főzünk, a csomagoláson található utasítások szerint, vagy a csontlében, egy másik, kisebb fazékba mérve belőle. Aki szereti a levesben kifőtt zöldséget és húst fogyaszthatja előételként, mustárral vagy tormával körítve.'),
(10, 'bácskai rizses hús', 'bacskai-rizses-hus', 75, 'megfizethető', 'bacskai-rizses-hus.jpg', 'A kockára vágott hagymát megpirítjuk a felforrósított zsíron, hozzáadjuk a szintén kockára vágott paprikát, együtt is pirítjuk kicsit, majd lehúzzuk a tűzről és elkeverjük benne a pirospaprikát. Hozzáadjuk a feldarabolt paradicsomokat, visszatesszük a tűzre, és beletesszük a felkockázott húst. Megsózzzuk, megborsozzuk, felengedjük vízzel, és a zúzott fokhagymát is beletesszük. Lefedve, a vizet mindig pótolva nem egészen puhára pároljuk a húst. Amikor majdnem puha, beletesszük az alaposan megmosott rizst és felöntjük 4 dl vízzel, hogy az egészet jól ellepje. Majd a lábost a már 150 fokra előmelegített sütőbe tesszük, és addig hagyjuk benne, amíg a rizs felszívja a vizet. Félidőben megkeverjük. Ekkor elzárjuk a sütőt, és még így is hagyjuk benne kb. 10 percig. Tálalás előtt még megszórjuk egy pici borssal.'),
(11, 'pásztortarhonya', 'pasztortarhonya', 30, 'megfizethető', 'pasztortarhonya.jpg', 'Egy serpenyőben olajat hevítünk, amin megfonnyasztjuk az apróra felkockázott vöröshagymát. Hozzászórjuk a tarhonyát és a karikára vágott kolbászt - kb. 5 perc alatt egy kicsit megpirítjuk rajta. Belerakjuk a szintén apró kockákra felvágott paprikát és paradicsomot és 1-2 percig kevergetjük. Pirospaprikával meghintjük. Hozzáadjuk a kockára vágott burgonyát és annyi vízzel öntjük fel, hogy a folyadék 2 ujjnyira ellepje azt. Sózzuk, borsozzuk ízlés szerint. Lefedve puhára főzzük. Ha szükséges pótoljuk időközben az elfőtt folyadékot.'),
(12, 'túrógombóc', 'turogomboc', 60, 'átlagos', 'turogomboc.jpg', 'A túrót gondosan áttörjük, majd hozzáadjuk a tojásokat, összekeverjük. A 2 dl búzadarát, a pici sót belekeverjük, és hagyjuk állni jó fél órát minimum, hogy a búzadara felszívjon egy kis nedvességet. Közben elkészítjük az édes mártást hozzá. A tejfölt, a habtejszínt és a cukrot összekeverjük, ha esetleg valaki édesebben szereti, tehet még hozzá cukrot. Addig keverjük, míg a cukor fel nem olvad benne. Felteszünk egy nagy lábasban vizet melegedni. A zsemlemorzsát egy egészen pici barna cukorral olajon elkezdjük pirítani. Nagyon kell figyelni, hiszen a cukor könnyen megéghet! Közben az elkészült masszából közepesen nagy golyókat formázunk, jól összenyomjuk, nehogy szétessenek majd főzés közben. Amikor a víz felforrt, beleteszünk 4-5-6 golyót a lábas méretétől függően, és amikor a gombócok feljöttek a víz tetejére, akkor a zsemlemorzsás keverékbe tesszük, és a lábast felemelve körkörös mozdulatokkal összerázzuk. Így egyenletesen befedett gombócokat kapunk. Ezt addig ismételjük, míg el nem fogynak a gombócok.'),
(13, 'halászlé', 'halaszle', 60, 'költséges', 'halaszle.jpg', 'A dunai halakat, 3,5 kg pontyot, és 1,5 kg vegyes halat (márnát, kárászt, törpeharcsát) gondosan megtisztítjuk. A vegyes halat sűrűn beirdaljuk. A pontyot irdalás után kétujjnyi vastag darabokra, a fejet pedig félbe vágjuk. Ezután lesózzuk, fűszerpaprikával meghintjük. Két órát hűtőben letakarva tároljuk. A vöröshagymát apróra daraboljuk, a bogrács aljára tesszük. Rákerül a befűszerezett hal. Vízzel felöntjük, és intenzíven forraljuk. 10 perc után rátesszük a fűszerpaprikát, a cseresznyepaprikát, s így még 30 percig forraljuk. Közben a frissen gyúrt gyufa tésztát külön vízben kifőzzük. A kifőtt tésztát a hallével tálaljuk, míg a halat esztétikusan felrakva, külön tálon kínáljuk.'),
(14, 'mákos guba', 'makos-guba', 30, 'olcsó', 'makos-guba.jpg', 'A kifliket 1 cm-es karikákra vágjuk. A tejet a vaníliarúd kikapart belsejével vagy egy csomag vaníliás cukorral felforraljuk. A kifliket a forró tejjel leöntjük, majd leszűrjük, és kinyomkodjuk belőle a tejet. Egy nagyobb jénai tálba egy réteg kiflit teszünk, majd porcukros mákot szórunk rá, megint kiflit és megint mákot, amíg elfogynak a hozzávalók. Ha marad még mák, szórjuk meg a tetejét is vele. Ha szeretnénk, akkor 7-8 percre berakhatjuk a sütőbe, de nem szükséges.'),
(15, 'töltött káposzta', 'toltott-kaposzta', 90, 'költséges', 'toltott-kaposzta.jpg', 'A káposztát egy fazékba tesszük, felöntjük vízzel, majd kis lángon, forrástól számítva kb. 10 percig főzzük. Ekkor óvatosan kivesszük, és hideg vízbe tesszük, hogy minél előbb lehűljön. Ezután leveleire szedjük, majd a középső, vastag, eres részét kivágjuk. A hagymát apróra vágjuk, hozzáadjuk a felhevített olajhoz, és pár perc alatt üvegesre pároljuk. Ezután levesszük a tűzről. A darált húst egy tálba tesszük, hozzáadjuk a pirospaprikát, a rizst, ízlés szerint sót és őrölt borsot, és alaposan összekeverjük. Ezután az elkészült töltelékkel megtöltjük az előkészített káposztaleveleket. A savanyú káposztát kissé kinyomkodjuk, hogy ne legyen nagyon savanyú, átmossuk, majd felvágjuk. A füstölt tarját nagyobb kockákra, a kolbászt karikára vágjuk. Egy tepsibe (vagy nagyobb lábasba) beletesszük a felkockázott tarját, majd ráterítjük a savanyú káposztát. Ezután megszórjuk a kolbászkarikákkal, ráhelyezzük  a megtöltött káposztát. (én kicsi mélyedéseket csináltam a savanyú káposztába, és abba helyeztem bele a tölteléket). A sűrített paradicsomot simára keverjük a vízzel, majd a káposztára öntjük (lepje el). Ezután fóliával lefedjük a tepsit, mielőtt a sütőbe helyeznénk. 180 fokra előmelegített sütőbe helyezzük és kb. 90 perc alatt készre pároljuk. Mire a töltelék, a káposzta és a füstölt húsok puhára főnek, a leve nagy része elpárolog, és kissé besűrűsödik. Tálaláskor tányérra helyezzük a tölteléket, mellékanalazzuk a savanyú káposztát a füstölt tarjával és a kolbásszal.'),
(16, 'tárkonyos palócleves', 'tarkonyos-palocleves', 90, 'megfizethető', 'tarkonyos-palocleves.jpg', 'A finomra aprított vöröshagymát és fokhagymát az olajon üvegesre pároljuk. Hozzáadjuk a felkockázott húst és megpirítjuk. Lehúzzuk a tűzről, megszórjuk őrölt paprikával, felöntjük egy kevés vízzel, és visszatesszük a tűzre. Hozzáadjuk a felaprított zöldpaprikát és a paradicsomot. Sóval, borssal, babérlevéllel és tárkonnyal ízesítjük. Takarék lángon, lefedve főzni kezdjük. A burgonyát megtisztítjuk és felkockázzuk. A zöldbabot ízlés szerinti darabokra vágjuk. Amikor a hús félpuha (kb. 20 perc múlva), hozzáadjuk a zöldbabot, felengedjük kb. 1,5 liter vízzel, és a köménnyel ízesítjük. Kb. 10 perc múlva hozzáadjuk a burgonyát, és teljes puhulásig főzzük. A tejfölt kikeverjük a liszttel, és hőkiegyenlítés után a leveshez adjuk. Újraforraljuk, és bőven megszórjuk felaprított friss petrezselyemmel. Végül pár csepp citromlével pikánsra ízesítjük.'),
(17, 'tarhonyaleves', 'tarhonyaleves', 45, 'átlagos', 'tarhonyaleves.jpg', 'Az apróra vágott hagymát olajon megdinszteljük. Hozzáadjuk a felkarikázott kolbászt, és megpirítjuk. Hozzáadjuk a tarhonyát, és halványbarnára pirítjuk. Beletesszük a felkockázott paradicsomot és paprikát, megsózzuk és megszórjuk pirospaprikával. Felengedjük 1 liter vízzel, és 10 percig főzzük. Beletesszük a felkockázott krumplit, és további 15-20 percig főzzük, amíg a tarhonya és a krumpli is megpuhul.'),
(18, 'borsos tokány', 'borsos-tokany', 60, 'átlagos', 'borsos-tokany.jpg', 'A húst alaposan megmossuk, lecsöpögtetjük, és vékony csíkokra vágjuk. A hagymát apró darabokra vágjuk, a paprikát és a paradicsomot felkockázzuk. A szalonnát csíkokra vágjuk, zsírjára pirítjuk, hozzáadjuk az olajat, majd megdinszteljük rajta az apróra vágott hagymát. Hozzáadjuk a húst, és fehéredésig pirítjuk. Megsózzuk, megborsozzuk, és beleszórjuk a paprikát és a paradicsomot. Összekeverjük, és felöntjük annyi vízzel, hogy ellepje. Kb. 40-45 percig főzzük, amíg a hús puha lesz, és elfő a víz. Sós és olajos vízben a csomagoláson található uatsítás szerint al dentére főzzük a tésztát. A tokányt a frissen főtt tésztával tálaljuk.'),
(19, 'túrós csusza', 'turos-csusza', 45, 'megfizethető', 'turos-csusza.jpg', 'A tésztát a csomagoláson található előírás szerint forró, sós vízben kifőzzük, majd lecsepegtetjük. A szalonnát kockára vágva pörcösre sütjük. Amikor kisült, a zsírját a tésztára öntjük, hozzákeverjük a fele túrót, a tejföl felét és a pörcök felét is, megsózzuk. Tűzálló tálban sütőbe tesszük, tetejére tejfölt simítunk és az egészet összesütjük. Tálaláskor teszünk még rá túrót, tejfölt és pörcöt.'),
(20, 'tökfőzelék', 'tokfozelek', 30, 'olcsó', 'tokfozelek.jpg', 'A gyalult tököt besózzuk, meglocsoljuk egy kevés ecettel, majd kb. fél órát állni hagyjuk, hogy levet eresszen. Az apróra vágott vöröshagymát és a kaporlevelet kissé megfonnyasztjuk, majd a cukrot hozzáadva karamellizáljuk. Hozzáadjuk a hámozott és cikkekre vágott paradicsomot, és a felszeletelt paprikát. Együtt pirítjuk őket, majd megszórjuk pirospaprikával, rátesszük a tököt, összekeverjük, és fedő alatt alacsony hőmérsékleten 10-15 perc alatt puhára pároljuk. A tejfölt simára keverjük a liszttel, és a megpuhult tökre öntjük, majd még egyszer felforraljuk. Utánízesítjük, ha szükséges.'),
(21, 'csirkepörkölt', 'csirkeporkolt', 75, 'olcsó', 'csirkeporkolt.jpg', 'A csirkecombokat megtisztítjuk, feldaraboljuk alsó-felső részre, majd besózzuk. A hagymát tisztítás után finomra vágjuk, majd felhevített zsírban megdinszteljük. Mikor aranysárga, a tűzről lehúzva megszórjukpirospaprikával, hozzátesszük a lecsót - vagy 2-2 db felkockázott friss paradicsomot és paprikát - majd a tűzre visszatéve lepirítjuk, felöntjük egy kevés folyadékkal, ismét zsírjára pirítjuk, majd újra felöntjük kevés folyadékkal. Ezt a műveletet szakaszos párolásnak hívják, így érjük el, hogy a pörköltszaftunk sűrű és zamatos legyen. Ezután beletesszük a darabolt csirkecombokat, és azokat, folyamatos folyadékpótlás mellett puhára pároljuk. Ha szükséges, sózzuk, vagy aki csípősen szereti, tehet hozzá csípős paprikát.'),
(22, 'gulyásleves', 'gulyasleves', 90, 'költséges', 'gulyasleves.jpg', 'A húsból a szokásos módon, jó sok hagymával pörköltet készítünk beletesszük az erős paprikát is. Ahol gyerek is eszik belőle, ott csak a tányéron tegyünk bele erős paprikát. A zöldségeket feldaraboljuk és sós, ételízesítős vízben feltesszük főni, csak éppenhogy ellepje. Amikor a hús már puha, hozzáöntjük a zöldséget, ekkor tesszük bele a kockára vágott krumplit, a köménymagot és a borsot. Addig főzzük így együtt, amíg a krumpli is puha lesz. Puha kenyérrel tálaljuk.'),
(23, 'bakonyi sertésszelet', 'bakonyi-sertesszelet', 90, 'átlagos', 'bakonyi-sertesszelet.jpg', 'A paradicsomot, zöldpaprikát és a gombát felvágjuk. A szalonnát nagyobb, a hagymát pedig kisebb darabokra kockázzuk. A karajt felszeleteljük, megmossuk, kicsit kiklopfoljuk, majd megsózzuk. A szalonnát zsírjára sütjük, majd egy tányérra szedjük. A hússzeleteket beleforgatjuk a lisztbe, és a szalonna visszamaradt zsírjában mindkét oldalát pár perc alatt megsütjük. A felszeletelt gombát a visszamarad zsíron megpirítjuk (ha szükséges teszünk hozzá zsírt), majd ezt is egy tányérra szedjük. Az apróra vágott hagymát üvegesre pároljuk, majd hozzáadjuk a felvágott paprikát és paradicsomot. Sózzuk, borsozzuk, meghintjük fűszerpaprikával, majd rátesszük a hússzeleteket, és annyi vizet öntünk rá, hogy jól ellepje. Az edényt lefedjük, időközönként megkeverjük, és, ha szükséges, öntünk hozzá vizet. Kb. 1 órát főzzük, amíg a hús megpuhul. Közben, a csomagoláson található utasítás szerint kifőzzük a tésztát. Ha megpuhult a hús, kivesszük egy tányérra. A lisztet a tejföllel kikeverjük, és a forró szaftból 1-2 merőkanálnyit hozzákeverünk, majd visszaöntjük a szafthoz (behabarjuk). Visszatesszük a húst, hozzáadjuk a megpirított gombát és a zsírjára sült szalonnát. Összekeverjük, majd még egy-két percig főzzük, majd tálaljuk.'),
(24, 'sertéspörkölt tarhonyával', 'sertesporkolt-tarhonyaval', 60, 'megfizethető', 'sertesporkolt-tarhonyaval.jpg', 'A húst kockára, a hagymákat apróra vágjuk, a paprikákat és a paradicsomot feldaraboljuk. Egy serpenyőben a zsíron megdinszteljük a hagymát, majd a húst, és hozzáadjuk a paprikát, a paradicsomot, a csilipaprikát, a fokhagymát és a felaprított medvehagymát. Megsózzuk, megborsozzuk, megszórjuk pirospaprikával és egy kevés köménymaggal, majd hozzáöntünk egy kevés vizet. Zsírjára sütjük, majd ismét felöntjük egy kevés vízzel. A tarhonyát a zsíron megpörköljük, megsózzuk, megborsozzuk, és felöntjük vízzel, és puhára főzzük. Amikor a pörkölt már majdnem kész, hozzáöntjük a vörösbort. A pörköltet a tarhonyával, tejföllel, csilivel és medvehagymával tálaljuk.'),
(25, 'toroskáposzta', 'toroskaposzta', 75, 'olcsó', 'toroskaposzta.jpg', 'A lapockát megmossuk, és kb. 2 cm-es kockákra vágjuk. A hagymát felaprítjuk, majd kevés olajon megdinsztelve hozzáadjuk a húskockákat. Sóval, borssal fűszerezzük, összekeverjük. Ezután megszórjuk pirospaprikával. Felöntjük 1 dl vízzel, és hozzáadjuk a babérleveleket. Kis tűzön 3 percig főzzük. A savanyú káposztából kinyomkodjuk a levét (kimosni nem kell), majd kicsit összeaprítjuk. A húshoz hozzáadjuk a káposztát, felengedjük 2 dl vízzel, és jól átkeverve addig főzzük, amíg meg nem puhul (kb. 1 óra). Kevés olajból és lisztből rántást készítünk, amit a megfőtt ételbe keverünk. 5 percig forraljuk. Tálaláskor tejföllel kínáljuk.'),
(26, 'harcsapaprikás', 'harcsapaprikas', 45, 'költséges', 'harcsapaprikas.jpg', 'A füstölt szalonnát kockákra vágjuk, és egy teflon serpenyőben, lassú tűzön ropogósra kisütjük. A ksiült zsírt félretesszük. Mire kisült a szalonna, addigra felforrt a víz, amibe most beletesszük a tésztát, és 8 percig főzzük, majd leszűrjük. A kifőtt csuszát meglocsoljuk 3 ek szalonnazsírral majd közé keverjük a túrót, és a tetejét meghintjük a sült szalonnakockák felével. Ízlés szerint meg is sózhatjuk. Ha készen van a harcsafilé, egy arra alkalmas edényben feltesszük hevülni a szalonna zsírját. A harcsafilét egyforma, kb. 2-3 cm-es kockákra vágjuk és megsózzuk. Egy tálba beletesszük a lisztet, a fokhagymát, ízlés szerint borsot, sót és 1 kávéskanál őrölt fűszerpaprikát, majd jól összekeverjük. A halkockákat egyesével megforgatjuk a fűszeres lisztben (úgy, hogy minden oldala fedve legyen), és 2-3 percig sütjük a szalonna zsírjában, majd kiszedjük. A megmaradt zsírban az apró kockára vágott hagymát üvegesre pirítunk). Hozzátesszük az apróra vágott paprikát, főzzük így 3 percet, majd az apróra vágott paradicsomot, ezzel is főzzük még 2 percig , meghintjük a tetejét a maradék pirospaprikával, sóval, borssal, végül leöntjük 1 dl vízzel. Az így kapott szaftba óvatosan beletesszük a halat, és kb. 5 percig főzzük. A megmaradt fűszeres lisztből, valamint még 1 ek lisztből, 1 dl vízből és a tejföl elegyéből habarást észítünk, majd felöntjük vele a halat. Így főzzük még 3-5 percet, és tálaljuk a túrós csuszával és a szalonnapörccel.'),
(27, 'hurka burgonyával', 'hurka-burgonyaval', 90, 'megfizethető', 'hurka-burgonyaval.jpg', 'Előző este a rizst elkészítjük. 4-5 evőkanál zsíron (vagy olajon) a megmosott rizst enyhén megpirítjuk, borsozzuk és sós vízzel felöntjük. Fedő alatt 5-6 percig főzzük, közben kevergetjük. 200 fokra előmelegített sütőbe tesszük, és a tűzhelyet lekapcsoljuk. A sütőben megdagad a készre főtt rizs. Másnap egy nagy edénybe kiöntjük a rizst, hozzákeverjük a beáztatott, kicsavart zsemlékeket és sóval, borssal, majoránnával fűszerezzük. Az apróra vágott vöröshagymát zsíron átfuttatjuk, majd hozzákeverjük. Ekkor két részre osztjuk. A felébe vért keverünk, a másik felébe főtt, darált májat. A langyos vízbe áztatott belet megfelelő nagyságúra vágjuk, és a kétféle töltelékkel megtöltjük. Vizet forralunk egy nagy lábasban, és a hurkát kifőzzük. Újraforrástól számítva 1 perc múlva kivehető (ekkor csak gyönyözzön a víz). Gyúrótáblákra rakjuk a kész hurkákat, terítővel betakarjuk őket, ettől ugyanis szép fényesek lesznek. Sütéskor a hurkákat zsírral kent tepsibe fektetjük. A burgonyát meghámozzuk, megmossuk, majd apró darabokra vágjuk, tepsibe tesszük, és fóliával letakarva 200 fokon sütjük, míg a burgonya egy kicsit megpuhul (kb. 13-15 perc alatt). Ezután a hurka mellé tesszük, letakarjuk fóliával. 5 perc sütés után vékony tűvel megszurkáljuk a hurkát. Ezután levesszük a fóliát, és kb. 20 perc alatt az egészet szép pirosra sütjük.'),
(28, 'pacalpörkölt', 'pacalporkolt', 90, 'megfizethető', 'pacalporkolt.jpg', 'Az abároláshoz a csíkozott, előfőzött pacalt felöntjük annyi vízzel, amennyi ellepi. Sózzuk, kettévágott vöröshagymával, babérral, borssal lassú tűzön kb. 1 órán át főzzük. A hagymát, a babért és a borsot eltávolítjuk, a levét leöntjük. A pacalt langyos vízben átmossuk, leszűrjük és lecsepegtetjük. A szalonnát vékony csíkokra aprítjuk, a zsírban kisütjük. A finomra vágott vöröshagymát a szalonna zsírjában megpirítjuk, majd ebben a zúzott fokhagymát is megfuttatjuk. Rátesszük a lecsóalapot, megszórjuk őrölt paprikával, belekeverjük a pacalt a szalonna bőrével együtt. Felöntjük annyi vízzel, amennyi szűken ellepi, fűszerezzük köménnyel, ízlés szerint sóval, borssal, csilivel és Piros Arannyal, majd lassú tűzön főzzük. Néha megkeverjük, a vizet szükség szerint pótoljuk. Addig főzzük, amíg majdnem puha lesz, majd vörösbort öntünk hozzá, és teljes puhulásig főzzük. Közben sós vízben megfőzzük a hasábra vágott burgonyát. A pacalpörköltet a főtt burgonyával és savanyúsággal kínáljuk.'),
(29, 'betyárleves', 'betyarleves', 75, 'megfizethető', 'betyarleves.jpg', 'Olajon megdinszteljük a kockára vágott hagymát. Meghintjük fűszerpaprikával, hozzáadjuk az apróra vágott húst, ízlés szerint sózzuk, fűszerezzük.Felengedjük 3 dl vízzel, és félpuhára főzzük. Beletesszük az apróra vágott paprikát, paradicsomot, gombát és a kaprot, és felengedjük vízzel. Amikor megpuhult a hús, behabarjuk a liszttel elkevert tejföllel.'),
(30, 'székelykáposzta', 'szekelykaposzta', 90, 'megfizethető', 'szekelykaposzta.jpg', 'A káposztát vékony csíkokra szeljük. Egy kb 3-4 literes üvegbe rakjuk. Literenként 1 evőkanál sóval vizet forralunk fel és a káposztára öntjük. A sós vízzel felöntött káposztát a napra kitesszük, ahol legalább 5 napig érleljük. A tetejét egy kis tányérral lefedjük. A tetejére nem teszünk sem kenyeret. Öt nappal később megpucoljuk és felaprítjuk a hagymát. Egy kevés zsíron megdinszteljük, rádobjuk a húst fehéredésig kevergetjük, majd az összes fűszert hozzáadjuk és annyi vízzel felengedjük, ami ellepi. Ekkor levesszük a tűzről. Egy kerámia edénybe öntjük a káposztát, levével együtt, erre került a fűszeres hús. Összekeverjük, lefedjük és a hideg sütőbe rakjuk. 170 fokon 1.5 órán át sütjük (alsó-felső sütéssel). Rántást nem készítünk rá, csak tejföllel tállaljuk.'),
(31, 'gombapaprikás', 'gombapaprikas', 30, 'átlagos', 'gombapaprikas.jpg', 'A megtisztított, és apró kockára vágott vöröshagymát olajon megdinszteljük, majd meghintjük a fűszerpaprikával, és hozzáadjuk a sűrített paradicsomot is, elkeverjük. Hozzáadjuk a szeletelt gombát, sózzuk, borsozzuk, és fedő alatt megpároljuk. Ha nem enged elég vizet, ezt pótolhatjuk kevés víz hozzáadásával. Közben a tejfölt csomómentesre keverjük a liszttel. Miután a gomba kellően összeesett és megpuhult, belekeverjük a tejfölt is. Köretnek jól illik mellé a rizs, galuska, de egészségesebb változatként a bulgurral is remek párost alkotnak.'),
(32, 'cigánypecsenye', 'ciganypecsenye', 30, 'megfizethető', 'ciganypecsenye.jpg', 'Először készítsük el a pácot, amiben a húsok pihenni fognak: öntsük egy tálba az olajat, nyomjunk hozzá a fokhagymát, szórjuk hozzá a fűszerpaprika felét, majd sózzuk, borsozzuk, és alaposan elkeverjük, és belehelyezzük a - klopfolatlan - sertéstarját. A krumplit meghámozzuk,  hosszában négyfelé vájuk, majd megszórjuk sóval, borssal, majoránnával, oregánóval, a fűszerpaprika másik felével, majd meglocsoljuk, egy kevés olajjal, és összekeverjük az egészet. 200 fokra előmelegített sütőbe tesszük kb. 40-45 percre a középső rácsra. 10-15 percenként átkeverjük. Ha már puha, akkor maximumra kapcsoljuk a sütőt, hadd piruljon a köret! A szalonnát félujjnyi vastagra vágjuk, majd bemetéljük a háromnegyed részükig, és egy serpínyőben piros-ropogósra sütjük, majd kivesszük. A szalonnazsírba beletesszük a hússzeleteket, és mindkét oldalukat  4-5 percig sütjük, majd kivesszük a serpenyőből. Ekkor nagyon finom, szaftos, omlós húst fogunk kapni. A kisült, ropogós fűszeres krumplikat egy szép nagy tálra helyezzük, ráhelyezzük a húsokat, megkenjük őket a másik fél adag zúzott fokhagymával, a tetejére rakjuk az időközben fűszerpaprikába mártott füstölt szalonnát (csak a tetejét kell a paprikába mártani), majd mellé halmozzuk a finoman csípős savanyúságokat.'),
(33, 'töltött-rántott csirkemell', 'toltott-rantott-csirkemell', 30, 'megfizethető', 'toltott-rantott-csirkemell.jpg', 'A csirkemelleket szétnyitjuk, kiklopfoljuk, megsózzuk. A paprikát, paradicsomot karikákra vágjuk. Mindegyik csirkemellre teszünk 1-1 szelt bacont, füstölt sonkát, trappista sajtot, 2 karika paradicsomot és 4-5 szelet csípős paprikát. A csirkemelleket összehajtjuk, lisztbe, tojásba, zsemlemorzsába forgatjuk, és bő olajban kisütjük. Zöldséges rizzsel tálaljuk.'),
(34, 'csülökpörkölt', 'csulokporkolt', 90, 'megfizethető', 'csulokporkolt.jpg', 'A csülköt kicsontozzuk, de egyszerűbb ha a hentesnél eleve kicsontozva kérjük. A húst bőröstül nagyobb kockákra vágjuk, a combot szintén hasonló méretűre kockázzuk fel. Némi zsíron pirítsuk zsírjára a kockára vágott szalonnát, majd hozzáadjuk a szintén felkockázott vöröshagymát és üvegesre pirítjuk. Ezután jöhet hozzá a hús, pirítsuk pár percig, ha már kezd fehéredni, akkor a tűzről félrehúzva az őrölt fűszerpaprikával megszórjuk, ügyelve, hogy ne égjen meg. Annyi vízzel felöntjük, hogy csak félig lepje el. Ezután mehet mellé az apróra vágott paprika és paradicsom. Ízesítjük sóval, borssal, őrölt köménnyel, aki szereti, ízlés szerint csípős paprikakrémmel. Bográcsban főzve ügyeljünk arra, hogy gyakran keverjük meg a pörköltet, nehogy leégjen, odakozmáljon! A zúzott fokhagymát is hozzáadjuk és már tényleg csak annyi a dolgunk, hogy türelmesen kivárjuk ameddig a hús megpuhul. (Nálam ez kb. másfél óra volt.) Főtt burgonyát és uborkasalátát kínáltam hozzá, ja és a friss kenyér kötelező volt, mert az isteni szaftot muszáj volt tunkolni!'),
(35, 'birkapörkölt', 'birkaporkolt', 90, 'megfizethető', 'birkaporkolt.jpg', 'A szalonnát kockákra vágjuk, kevés zsíron üvegesre sütjük. A nagyobb darabokra vágott vöröshagymát megdinszteljük, és köménymagot is pirítunk rajta. Először a feldarabolt körmöt, majd a lefaggyúzott birkahúst hozzáadva, addig pirítjuk, míg a hús enyhén elfehéredik. Megsózzuk, majd felöntjük annyi vízzel, hogy éppen ne lepje el. A hús is enged kevés lét! Az apróra darabolt paprikát, és a paradicsomot is a bográcsba tesszük. Lassú tűzön főzzük, időnként megforgatva a bográcsot. Nem kavarjuk! Hozzászórjuk a szemes borsot, (ha őrölt borsot használunk, később adjuk hozzá, mert a bogrács aljára éghet) a félbevágott kicsumázott csípős paprikát, a szétnyomott, felaprított fokhagymát és az összekötözött kis csokor kakukkfüvet is a bográcsba tesszük. Mikor felforrt, kóstoljuk meg. Ízesíthetjük kevés sóval szükség szerint. Ha kell a főzővizet pótoljuk időnként! Amikorra a köröm csontjairól kezd lefőni a hús, addigra fő meg a birkahús is. Kóstoljuk meg mindkét húsfélét is! Amikor úgy érezzük elkészült a hús, kivesszük a kakukkfű csokrot, elkeverjük vörösborban az őrölt pirospaprikát, amit kevés főzőlével temperálunk, majd hozzákeverünk a pörköltünkhöz. Ha egyneművé válik a pörkölt szaftja, tálalhatjuk.'),
(36, 'marhapörkölt', 'marhaporkolt', 90, 'költséges', 'marhaporkolt.jpg', 'A szalonnát felcsíkoztam, majd zsírjára pirítottam. A sült szalonnát kivettem, a zsírhoz hozzáadtam a kockákra vágott hagymát és a szétnyomott fokhagymát. Kicsit dinszteltem, majd hozzáadtam a köménymagot, amit kipattogtattam (megpirítottam). A kockázott marhalábszárat is beletettem, valamint a felkarikázott paprikának a felét, és a paradicsomokat egészben úgy, hogy a csumáját kivágtam, és kereszt alakban bevágtam. Később a paradicsomok héját le tudtam húzni, azt eltávolítottam a bográcsból. A húst kicsit pirítottam, míg ki nem fehéredett. Felöntöttem annyi vízzel, hogy éppen ne lepje el, majd megsóztam. A bográcsba került a felkarikázott paprika másik fele és az erős paprika is félbevágva. Ezután 2 órán át főtt, a bográcsot időnként megforgatva, és az elfőtt levet időnként pótolva. Mikor úgy éreztem, megfőtt, a pirospaprikát csomómentesre kevertem vörösborban, és hozzáöntöttem a bogrács tartalmához. Rövid rotyogtatás után a pörkölt elkészült. Főtt krumplival, friss kenyérrel, savanyúsággal tálaltam.'),
(37, 'zöldbabfőzelék', 'zoldbabfozelek', 60, 'átlagos', 'zoldbabfozelek.jpg', 'A zöldbabot megtisztítjuk, végeit eltávolítjuk, és 2-3 cm-es darabokra vágjuk, megmossuk. Kb. 1-1,5 l vízben feltesszük főni. Ízesítjük sóval, ételízesítővel, babérlevéllel, és beletesszük egészben a vöröshagymát, valamint a zúzott fokhagymát. Puhára főzzük (kb. 45 perc), majd a hagymát eltávolítjuk. A lisztből az olajjal vagy zsírral rántást készítünk, a tűzről félrehúzva hozzáadjuk a pirospaprikát, a hideg vízzel simára keverjük, és berántjuk a főzeléket. A tejfölt is hozzákeverjük, ha kell, pici ecettel még ízesítjük.'),
(38, 'kolbászos-sonkás-rakott tarja', 'kolbaszos-sonkas-rakott-tarja', 90, 'megfizethető', 'kolbaszos-sonkas-rakott-tarja.jpg', 'Egy tűzálló tál aljára terítünk 4 szelet tarját, sózzuk, borsozzuk, majd mindegyik húsra 1-1 szelet angolszalonnát vagy sonkát teszünk. Tisztított, karikára vágott vöröshagymával beborítjuk, majd a lehéjazott, vékonyra szeletelt kolbász következik a sorban. Aztán a megmaradt 4 hússzelettel beborítjuk az egészet. A tejszínt összekeverjük a ketchuppal, a darált dióval, sóval, és nyakon öntjük vele a húst. A tálat lefedjük, előmelegített forró sütőben közepes lángon 1 óra 25 percen át sütjük. Burgonyakrokett a hozzáillő köret.'),
(39, 'törtpaszuly', 'tortpaszuly', 45, 'olcsó', 'tortpaszuly.jpg', 'A babot odatesszük sós vízben főzni. Amíg a bab fől, addig a hagymát megpucoljuk, karikára vágjuk. Zsírban puhára megdinszteljük, sót teszünk bele, a végén pirospaprikát is. Ha a bab megfőtt, leszűrjük. De a levét nem öntjük ki, félretesszük. A főtt babot vagy krumplitörővel összetörjük, vagy húsdarálón ledaráljuk kis főző lével, hogy könnyebben lehessen vele dolgozni. Belerakunk 1-2 ek lisztet, attól függően, hogy mennyire sűrűre szeretnénk \"sűríteni\". Utána a babpürét összerottyantjuk. Tálaláskor egy adag babot teszünk a tányérra, majd a tetejére a dinsztelt hagymából teszünk ízlésünk szerinti mennyiséget. Friss kenyérrel szoktuk tunkolni, és fejes saláta is nagyon finom hozzá. A bab félretett főzőlevéből főzhetünk finom levest. A lébe teszünk egy kanál dinsztelt hagymás zsírból, kevés ételízesítőt. Felfőzzük. A főtt babból is lehet pár szemet beletenni. (Valahol tesznek bele 2-3 db sárgarépát, 1 fehérrépát is.) Közben készítünk reszelt tésztát (1 tojás, kevés finomliszt, több rétesliszt, kevés só), jó keményre összegyúrjuk a hozzávalókat és a sajtreszelő nagy lyukú részén lereszeljük. Ezt a tésztát a levesbe főzzük és tálalunk.'),
(40, 'kolbászos-hagymás bab', 'kolbaszos-hagymas-bab', 75, 'megfizethető', 'kolbaszos-hagymas-bab.jpg', 'A szalonnát vékony, apró csíkokra vágjuk bőröstől, nehogy nagyon szétfőjön. A vöröshagymát vékony cikkekre felszeleteljük. A szalonna zsírját az olajon kisütjük lassan, hogy a szalonna meg ne égjen, és ne legyen túl száraz. Utána a szalonnát kiszedjük, és a zsírjában a hagymát üvegesre pároljuk. Közben a felszeletelt kolbászt 3 dl vízben előfőzzük, utána a főzőlével együtt a megpárolt hagymához öntjük. (Az előfőzés kb. 10-15 percig tartson.) Visszarakjuk bele a kiszedett szalonnacsíkokat, és újabb 10-15 percig összeforraljuk, vigyázva, hogy oda ne kapja az alját. Ezután beletesszük a paradicsomlevet és a leszűrt babkonzervet, és 5-10 percig összeforraljuk. Puha fehér kenyeret adunk hozzá. Nagyon finom, kiadós, laktató étel.'),
(41, 'rakott káposzta', 'rakott-kaposzta', 90, 'megfizethető', 'rakott-kaposzta.jpg', 'A szalonnát kakastaréjra darabolom, a zsírját – nem teljesen - lassan kisütöm, a szalonnát félreteszem. Kb. fele mennyiségű szalonna zsiradékban a fele mennyiségű kockázott vöröshagymát megdinsztelem, majd a fokhagymát is megfuttatom, a húst rajta fehéredésig átsütöm, és a szokásos módon a pirospaprikával, lecsóval, sóval, borssal, őrölt köménnyel, majoránnával, piros arannyal, ételízesítővel fűszerezett pörköltet készítek, a vége felé borral meglocsolva, de nem sütöm a végén zsírjára, mert jó, ha szaftos marad. A rizst az olajon megfuttatom, kétszeres mennyiségű forró vízzel felöntöm, sóval, borssal, ételízesítővel puhára párolom. A káposztát kimosom, kinyomkodom, néhány helyen a hosszú szálakat átvágom. A zsiradék másik felében a cukrot karmellizálom, a maradék félfőre aprított vöröshagymát üvegesre párolom, a káposztát a babérral, egész köménnyel, egy kis pohár vízzel kb. 1/2 órát párolom. A kolbász bőrét lehúzom, felkarikázom. Egy nagy tepsit (30x40 cm.) kizsírozok, a káposzta felét elterítem benne. Rákanalazom a rizst, a fele mennyiségű tejföllel lekenem. A pörköltet a szaftjával rámerem, a kolbászkarikákat elosztom rajta, beborítom a maradék káposztával, a maradék tejföllel bevonom. A kakastaréjokat a tetejére helyezem, fedetlenül, előmelegített 210 fokos sütőbe tolom. Kb. 45 percig sütöm, majd légkeverésre kapcsolom a sütőt, és kb. 15 percig pirítom, ameddig a teteje enyhén megpirosodik. Pihentetem, hűtöm, kb. 1 adagos kockákra szeletelem. Tálalásnál tányérra emelem, igény szerint a kakastaréjjal és tejföllel tálalom.'),
(42, 'töltött karaj rántva', 'toltott-karaj-rantva', 45, 'megfizethető', 'toltott-karaj-rantva.jpg', 'A hússzeleteket kiklopfoljuk, sózzuk. A póréhagymát vastagabb szeletekbe vágjuk. Minden szelet húsra teszünk 1-1 szelet bacont, sajtot, 2-2 szelet póréhagymát és kolbászt. A húst felgöngyöljük, bepanírozzuk, és közepes hőfokon kisütjük. Szalmaburgonyát készítettem mellé.'),
(43, 'tejfölös nokedli', 'tejfolos-nokedli', 30, 'olcsó', 'tejfolos-nokedli.jpg', 'A szokásos módon nokedlit szaggatunk az enyhén majorannás vízbe. A szalonnát kisütjük, a leszűrt nokedlit ebben megpörgetjük. A tejfölbe időközben 2-3 gerezd fokhagymát zúzunk, tálaláskor ezzel locsoljuk meg a nokedlit. Szokatlan, de finom ízvilágot varázsol a fokhagyma és majoranna keveredése... Nagyon laktató és ízletes.'),
(44, 'krumplifőzelék', 'krumplifozelek', 30, 'olcsó', 'krumplifozelek.jpg', 'A hagymát megtisztítjuk, felkockázzuk, kevés olajon üvegesre dinszteljük, majd lehúzzuk a fazekat a tűzről, és megszórjuk pirospaprikával. A burgonyát megtisztítjuk, felkockázzuk, és a hagymára szórjuk, majd felöntjük annyi vízzel, ami épp csak ellepi. Sózzuk, babérlevéllel ízesítjük. Amíg megpuhul a krumpli (fedő alatt, takaréklángon), elkészítjük a habarást: összekeverjük a lisztet a tejföllel, és ha a burgonya kész, óvatosan hozzákeverjük úgy, hogy ne legyen csomós. Rottyantunk egyet rajta, és máris tálalhatjuk.');

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `receptek`
--
ALTER TABLE `receptek`
  ADD PRIMARY KEY (`ssz`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `receptek`
--
ALTER TABLE `receptek`
  MODIFY `ssz` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=45;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
